### ISSUE TITLE
LILYGO mic version 

### ISSUE THREAD

**Issue by jsBlackBelt** [petrepa/ESPHome-VideoDoorbell#2]
Hello,

Will this recipe also support the LILYGO with mic variant?
US $7.20 | LILYGO® TTGO T-Camera ESP32 WROVER & PSRAM Camera Module ESP32-WROVER-B OV2640 Camera Module 0.96 OLED
https://a.aliexpress.com/_m0MMHoZ

**Comment by petrepa** [comment]
I would guess this will fit if it has the same dimensions and the microphone component does not protrude into the 3D model. 

Take note that the model do not have any holes for the microphone inlet, so the model would maybe have to be modified to better work with a mic

**Comment by jsBlackBelt** [comment]
Hi,

Thanks for your response
I was asking with regards to the wiring and maybe future support for the mic, as it is not supported with the current code. 

Basically, if I purchase the board with the mic, will this yaml still work?

**Comment by petrepa** [comment]
As of now ESPHome have no support for microphone at all, so there will be no straightforward way to implement microphone functionality native in ESPHome 😕 
I guess you could make yourself some custom components by using additional libraries😊

I do not have a plan to further develop and add functionalities to this project myself 😅
