### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by bernardovalente** [petrepa/ESPHome-VideoDoorbell#4]
By chance did you have this error, if so how did you solved it?

Operating environment/Installation (Hass.io/Docker/pip/etc.):

Hass.io (vm)

ESP (ESP32/ESP8266, Board/Sonoff):

LILYGO TTGO T-Camera ESP32

ESPHome version (latest production, beta, dev branch)

DEV

Description of problem:

Build fails

Problem-relevant YAML-configuration entries:

esphome:
  name: ttgo_campainha
  platform: ESP32
  board: esp-wrover-kit

Logs (if applicable):

Compiling /data/ttgo_campainha/.pioenvs/ttgo_campainha/src/esphome/components/esp32_camera/esp32_camera.cpp.o
Compiling /data/ttgo_campainha/.pioenvs/ttgo_campainha/src/esphome/components/sensor/automation.cpp.o
Compiling /data/ttgo_campainha/.pioenvs/ttgo_campainha/src/esphome/components/sensor/filter.cpp.o
Compiling /data/ttgo_campainha/.pioenvs/ttgo_campainha/src/esphome/components/sensor/sensor.cpp.o
src/esphome/components/esp32_camera/esp32_camera.cpp: In member function 'virtual void esphome::esp32_camera::ESP32Camera::dump_config()':
src/esphome/components/esp32_camera/esp32_camera.cpp:58:10: error: 'FRAMESIZE_QQVGA2' was not declared in this scope
     case FRAMESIZE_QQVGA2:
          ^
src/esphome/components/esp32_camera/esp32_camera.cpp: In member function 'void esphome::esp32_camera::ESP32Camera::set_frame_size(esphome::esp32_camera::ESP32CameraFrameSize)':
src/esphome/components/esp32_camera/esp32_camera.cpp:213:34: error: 'FRAMESIZE_QQVGA2' was not declared in this scope
       this->config_.frame_size = FRAMESIZE_QQVGA2;
                                  ^
*** [/data/ttgo_campainha/.pioenvs/ttgo_campainha/src/esphome/components/esp32_camera/esp32_camera.cpp.o] Error 1
========================== [FAILED] Took 1.92 seconds ==========================

**Comment by petrepa** [comment]
I am not familiar with this issue, but as I can see, you have also commented on this https://github.com/esphome/issues/issues/1884. 
Hopefully fixed in https://github.com/esphome/esphome/pull/1813

Hope you'll figure it out!
