### ISSUE TITLE
Alternative Case for TTGO T-Camera V1.6.2

### ISSUE THREAD

**Issue by TheDuffman85** [petrepa/ESPHome-VideoDoorbell#6]
Hi. I've created an alternative more water resistant case for the LILYGO TTGO T-Camera V1.6.2 board. Maybe this is helpful for somebody. 

https://www.thingiverse.com/thing:5988234

![PXL_20230421_152839499 PORTRAIT](https://user-images.githubusercontent.com/9296618/233932887-dd76f2f3-e1fe-4b2d-b619-cd6099e2c4b8.jpg)

**Comment by petrepa** [comment]
So cool! Thanks for sharing!

Added a [link in the readme](https://github.com/petrepa/ESPHome-VideoDoorbell#alternative-cases) to your design 😄 
[Related commit](https://github.com/petrepa/ESPHome-VideoDoorbell/commit/ee6faa91a6af8fb5412bba8c4f9a587247d9e8ed).
